repos:
  - repo: local
    hooks:
      - id: miniwdl-check
        name: Validate WDL files
        entry: miniwdl check
        language: python
        additional_dependencies: [miniwdl]
        files: '\.wdl$'
